---
title: "Report"
author: "psoeraas"
output: html_document
css: styles.css
---

This is a description of your beer and a list of details for brewing.


> Using the following file:
```{r, echo = FALSE}
suppressWarnings(library(ggplot2))
suppressMessages(suppressWarnings(library(plotly)))
stjerne <- data.frame(read.csv(file = "U:/R/HB/XY.csv"))
stjerne$Group <- factor(6)
south <- data.frame(read.csv(file = "U:/R/HB/XYsouth.csv"))
south$Group <- factor(7)
hopimg <- data.frame(read.csv(file = "U:/R/HB/XYhop.csv"))
hopimg$Group <- factor(7)
leaves <- data.frame(read.csv(file = "U:/R/HB/XYleaves.csv"))
leaves$Group <- as.factor(leaves$Group)
stem <- data.frame(read.csv(file = "U:/R/HB/XYstem.csv"))
stem$Group <- factor(10)
lineimg <- data.frame(read.csv(file = "U:/R/HB/XYline.csv"))
lineimg$Group <- factor(11)
brew <- data.frame(read.csv(file = "U:/R/HB/XYbrew.csv"))
brew$Group <- factor(7)
star <- data.frame(read.csv(file = "U:/R/HB/XYstar.csv"))
star$Group <- factor(11)



#Finding data
suppressWarnings(library(knitr))
closestTimestamp <- as.numeric(gsub(" ","", format(Sys.time(), "%d %m %y %H %M")))
files <- list.files("U:/R/HB")
timestamps <- as.numeric(gsub("[^$[:digit:]+{1}]", "", files))
for(item in 1:length(timestamps)){
  if(!is.na(timestamps[item])){
    timestamps[item] <- closestTimestamp - timestamps[item]
  }
}
timestamps <- ifelse(timestamps > 0, timestamps, NA)
timestamps <- ifelse(timestamps == min(timestamps, na.rm = T), timestamps, NA)

minimum <- grep(pattern = min(timestamps, na.rm = T), timestamps)
loadfile <- paste0("U:/R/HB/",files[minimum])
loadfile
load(file = loadfile)
#gravity_notes, IBU, df, BeerName, BeerType, hopgraph, maltgraph, Attgraph, img, Hops, Malts
```

## Name and type:

```{r, echo = FALSE, comment = NA}
#Name
returnlist[[4]][1]
#Type
returnlist[[5]][1]
```

## Profile:

```{r, echo = FALSE, results = "asis"}
#Hops
hoplist <- unlist(returnlist[10])
hopweights <- unlist(returnlist[[15]])
percentages <- list(unlist(lapply(hopweights, function(x) paste0(round(x/sum(hopweights)*100,2),"%"))))

#Malts
maltlist <- c(unlist(returnlist[[11]]$Malts))
#Yeasts
yeastname <- as.character(returnlist[[12]]$Name)
yeastatt <-as.character(returnlist[[12]]$Attentuation)
yeasttemp <- as.character(returnlist[[12]]$Temperature)



hops <- c()
malts <- c()

for(hop in 1:length(hoplist)){
  if(hop == 1){
    hops <- hoplist[[1]]
  } else {
    hops <- paste0(hops,", ", hoplist[[hop]])
  }
}

for(malt in 1:length(maltlist)){
  if(malt == 1){
    malts <- maltlist[[1]]
  } else {
    malts <- paste0(malts,", ", maltlist[[malt]])
  }
}



df <- data.frame(c("Hops","Yeast"), c(hops, yeastname))
df$Description <- c(percentages,paste("Attentuation:",yeastatt,", Temp. range:",yeasttemp))
colnames(df) <- c("Ingredients","Name","Description")
kable(df, format = "markdown")

```

```{r, echo = FALSE, results = "asis"}

#Malts

maltname <- unlist(returnlist[[11]]$Malts)
maltdesc <- returnlist[[11]]$description
malttype <- unlist(returnlist[[11]]$type)
maltprops <- returnlist[[13]]



maltdf <- data.frame(maltname,maltdesc, malttype, maltprops)

colnames(maltdf) <- c("Malt","Description","Type","%")
kable(maltdf, format = "markdown")

```



## Details:
```{r, echo = FALSE, results = "asis"}
Category <- c("Expected OG","Expected FG","Approx. SRM:","Approx. MCU:","Estimated ABV:","IBUs") 
Value <- c(returnlist[[1]][1],returnlist[[1]][5],returnlist[[1]][2],returnlist[[1]][4],returnlist[[1]][6],returnlist[[2]])

df <- data.frame(Category,round(Value,2))
colnames(df) <- c("Category","Value")
kable(df, format = "markdown")

```


## Instructions:
```{r, echo = FALSE}

Instruction <- c("Strike temp (c):", "Target mash temp (c):", "Strike vol (L):","Sparge vol (L):","Target vol (L):")
Value <- c(returnlist[[14]][4], returnlist[[14]][6],returnlist[[14]][1], returnlist[[14]][2], returnlist[[14]][5])


df <- data.frame(Instruction, Value)
kable(df, format = "markdown")
```


## Charts:

```{r, echo=FALSE, fig.width=10, fig.height=10, warning = FALSE, fig.align = "center"}

hopchart <- (returnlist[[6]])
suppressWarnings(hopchart)
```

```{r, echo=FALSE, fig.width=10, fig.height=5, warning = FALSE, fig.align = "center"}
#library(plotly)
maltgraph <- (returnlist[[7]])
# vs Gravity
ggplotly(maltgraph)
Attgraph <- (returnlist[[8]])
suppressWarnings(Attgraph)
```



```{r, echo = FALSE, fig.width = 12, fig.height = 8, warning = FALSE}

ggplot(data = south, aes(Xsouth,Ysouth, color = Group))+
  geom_point()+
  geom_point(data = hopimg, aes(Xhop,Yhop))+
  geom_point(data = leaves, aes(Xleaves,Yleaves))+
  geom_point(data = stem, aes(Xstem,Ystem))+
  geom_point(data = lineimg, aes(Xline,Yline))+
  geom_point(data = brew, aes(Xbrewnew,Ybrew))+
  geom_point(data = star, aes(Xstar,Ystar))+
  scale_colour_manual(values = c(
    #leaf
    "#63f200",
    #stem
    "#f28f00",
    #design
    "#00f28f",
    #leaves
    "#00f28f",
    "#00dcf2",
    "#0063f2",
    "#1600f2",
    #text
    "#f20063"
  ))+
    theme(
    plot.background = element_rect(fill = "#f0f0f0", colour = "#f0f0f0"),
    panel.background = element_rect(fill = "#f0f0f0", colour = "#f0f0f0"),
    panel.grid = element_line(colour = "#f0f0f0"),
    axis.ticks.margin = "none",
    axis.line=element_blank(),
    axis.title.x=element_blank(),
    axis.title.y=element_blank(),
    legend.position="none"
  )
  


```





